# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

# theme: "ocean"
# day_night: true
# font: Arial
# font_size: m
# SEO

appearance:
  theme_day: mtheme
  theme_night: mtheme
  font: minimal
  font_size: m

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: "Yangyang Li; Ph.D in Northwestern University"
    description: "My personal academic blog about Deep Learning and Bioinformatics"
    twitter: "yangyangliz5"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
  verification:
    google: ""
    baidu: ""

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: "© 2023 Me. This work is licensed under CC BY-NC-ND 4.0"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Site features
features:
  syntax_highlighter:
    theme_light: dracula
    theme_dark: dracula
  math:
    enable: true
  privacy_pack:
    enable: true
  repository:
    repo_url: "https://github.com/cauliyang/academic"
    content_dir: "content/en"
    repo_branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ""
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""
    giscus:
      repo: ""
      repo_id: ""
      category: ""
      category_id: ""
  search:
    provider: wowchemy
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false
  map:
    provider: ""
    api_key: ""
    zoom: 15
  feedback:
    responses:
      positive: "Glad to hear it! [Any ideas for improvements?](https://github.com/cauliyang/cauliyang.github.io/issues/new)"
      negative: "Sorry to hear that. [Please tell us how we can improve](https://github.com/cauliyang/cauliyang.github.io/issues/new)."

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true

# Localization

locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
  address_format: en-us
